### ISSUE TITLE
Login page: Mobile- Ability to scroll the login page once keypad is displayed 

### ISSUE THREAD

**Issue by ashika123** [ajency/PO#966]
Click on input field on the login page

Current: The page shows extra space and can be scrolled when clicked on input field
Expected: The page view should be same before and after the keypad is displayed

**Comment by renukaajency** [comment]
Tried a fix, seems to be working. But its not the proper way - but it seems it has worked for many. There might be other issues because of this but haven't encountered any yet.

This seems to be an [issue with ionic](https://github.com/ionic-team/ionic/issues/5432), it adds a padding bottom dynamically based on screen size (its probably to add some extra scroll when keypad is open but it doesn't remove it once keypad is closed)

**Comment by ashika123** [comment]
Resolved
